### PR TITLE
Build for aarch64

### PR DESCRIPTION
**Pull request by saraedum**

### CODE REVIEW

**Comment by saraedum** [comment]
@conda-forge-admin, please rerender.

**Comment by saraedum** [comment]
needs https://github.com/conda-forge/attr-feedstock/pull/1

**Comment by scopatz** [comment]
You can actually just add `libcap` to https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/migrations/arch_rebuild.txt and then attr will be picked up as part of the migration

**Comment by saraedum** [comment]
Thanks. I wasn't aware of that.

**Pull request closed without merging**
